swagger: "2.0"
info:
  version: 1.0.0
  title: iwantoplay-be
  description: Back-end for tha iwantoplay app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  CityBody:
    type: object
    title: city
    required:
      - name
    properties:
      name:
        type: string
        example: Cali
  SportBody:
    type: object
    title: city
    required:
      - name
    properties:
      name:
        type: string
        example: Futbol
paths:
  /cities:
    get:
      tags:
        - Cities
      description: Fetch all cities
      responses:
        200:
          description: Returns all cities
    post:
      tags:
        - Cities
      description: Create a new city
      parameters:
        - name: city
          in: body
          description: a city
          required: true
          schema: 
            $ref: "#/definitions/CityBody"
      responses:
        200:
          description: Returns all cities

  /cities/{id}:
    get:
      tags:
        - Cities
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the city to retrieve
          type: string
      responses:
        200:
          description: Return the city with the specified id
        404:
          description: City not found

  /sports:
    get:
      tags:
        - Sports
      description: Fetch all sports
      responses:
        200:
          description: Returns all sports
    post:
      tags:
        - Sports
      description: Create a new sport
      parameters:
        - name: sport
          in: body
          description: a sport
          required: true
          schema: 
            $ref: "#/definitions/SportBody"
      responses:
        200:
          description: Returns all sports

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification